"""
Module: nebius_llm_summarizer
Description: Handles communication with the Nebius Token Factory API (Llama 3.3 70B).
Utilizes Pydantic-enforced structured outputs to guarantee the API returns a valid JSON schema.
"""

import os
import logging
from openai import OpenAI
from pydantic import BaseModel
from typing import List

logger = logging.getLogger(__name__)

class RepoAnalysis(BaseModel):
    """
    Data Transfer Object (DTO) for repository analysis.
    This strictly enforces the schema for the LLM's structured output, 
    preventing application crashes caused by malformed JSON.
    """
    summary: str
    technologies: List[str]
    structure: str

class NebiusLLMSummarizer:
    """
    Interface for interacting with the Nebius LLM to extract 
    architectural insights from codebase context.
    """
    def __init__(self):
        # Securely load credentials from the environment; raise an immediate error if missing
        api_key = os.environ.get("NEBIUS_API_KEY")
        if not api_key:
            raise EnvironmentError("NEBIUS_API_KEY environment variable is not set. Please configure your .env file.")

        # Client initialization using the Nebius Studio OpenAI-compatible endpoint
        self.client = OpenAI(
            base_url="https://api.studio.nebius.ai/v1/",
            api_key=api_key
        )

    def extract_repo_insights(self, user_data: str) -> dict:
        """
        Processes the provided repository context and returns structured insights.
        
        Args:
            user_data: The compiled text containing the directory tree and truncated file contents
                       (generated by prompt_builder.py).

        Returns:
            dict: A dictionary containing the summary, technologies, and project structure.
        """
        
        # Upgraded System Prompt: Explicitly defines the detail level and format constraints 
        # to prevent the LLM from generating conversational filler or bloated arrays.
        system_instructions = (
            "You are an expert Senior Software Architect. Analyze the provided GitHub repository context.\n"
            "1. For 'summary': Provide a high-level, 2-3 sentence overview of the project's primary purpose.\n"
            "2. For 'technologies': Provide a flat array of strings containing ONLY the names of the main "
            "languages, frameworks, and tools used (e.g., ['Python', 'FastAPI', 'React']). Do not use full sentences.\n"
            "3. For 'structure': Provide a brief, architectural description of the core directory layout."
        )

        try:
            logger.info("Sending payload to Nebius API (Llama-3.3-70B-Instruct)...")
            
            # Utilize beta.chat.completions.parse for strict Pydantic schema validation
            response = self.client.beta.chat.completions.parse(
                model="meta-llama/Llama-3.3-70B-Instruct",
                messages=[
                    {"role": "system", "content": system_instructions},
                    {"role": "user", "content": user_data},
                ],
                response_format=RepoAnalysis,
                temperature=0.2 # Low temperature reduces hallucination and increases analytical consistency
            )

            # Convert the validated Pydantic object back into a standard Python dictionary
            return response.choices[0].message.parsed.model_dump()
            
        except Exception as e:
            # Graceful degradation: If the upstream Nebius API fails (timeout, 500 error, etc.),
            # we catch the exception and return a dictionary that our main.py error handler 
            # can recognize and process safely, rather than crashing the web server.
            logger.error(f"Failed to extract insights via Nebius LLM: {str(e)}")
            return {
                "summary": "Analysis unavailable due to upstream error.",
                "technologies": [],
                "structure": f"LLM Error: {str(e)}"
            }